name: marimo_client
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ“¦ Core
  provider: ^6.1.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1

  # ğŸ“· Media & Files
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  image: ^4.1.3

  # ğŸ–¼ï¸ UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^2.3.9
  table_calendar: ^3.2.0
  smooth_page_indicator: ^1.0.0

  # ğŸ“ ì§€ë„ & 3D
  flutter_naver_map: ^1.3.0
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.9.1
  webview_flutter: ^4.10.0

  # ğŸ“± ë””ë°”ì´ìŠ¤ ê¸°ëŠ¥
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0
  flutter_native_splash: ^2.4.5
  camera: ^0.11.1
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-splash.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/images/logo-splash.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true

  fonts:
    - family: Freesentation
      fonts:
        - asset: assets/fonts/Freesentation-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Freesentation-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Freesentation-3Light.ttf
          weight: 300
        - asset: assets/fonts/Freesentation-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Freesentation-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Freesentation-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Freesentation-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Freesentation-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Freesentation-9Black.ttf
          weight: 900
    - family: Esamanru
      fonts:
        - asset: assets/fonts/esamanru_light.ttf
          weight: 300
        - asset: assets/fonts/esamanru_medium.ttf
          weight: 500
        - asset: assets/fonts/esamanru_bold.ttf
          weight: 700

  assets:
    - .env
    - assets/images/
    - assets/images/cars/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/tires/
    - assets/models/uber_car.obj
    - assets/models/uber_car.mtl
    - assets/models/uberBlack.dae.glb
    - assets/models/generic_sedan.glb
    - assets/models/uberXL.glb
